
source 'https://rubygems.org'

gem 'activerecord'
gem 'sinatra-activerecord'
gem 'rake'
gem 'require_all'
gem 'sqlite3', '~> 1.3.6'
gem 'pry'
gem 'tty-prompt'
gem 'tty-table'
gem 'tty-spinner'
gem 'rainbow'
gem 'asciify', '~> 0.1.0'
gem 'iconv'
gem 'artii', '~> 2.1', '>= 2.1.2'
